# This service sets an LED color

uint32 index   # number of LED in a LED strip or other LEDs set
uint8 r        # red component of the color, 0..255
uint8 g        # green component of the color, 0..255
uint8 b        # blue component of the color, 0..255
---
bool success   # True if the call succeeded
string message # Error or informational message
